### PR TITLE
Check if there's a network request already in flight

### LINKED ISSUE #75: include-fragment-replaced triggered twice
Under some conditions, the 'include-fragment-replaced' and 'include-fragment-replace' events are triggered twice.

Fiddle: https://jsfiddle.net/36koL2mb/1/

Fiddle code:
```html
<script type="module" src="https://unpkg.com/@github/include-fragment-element@latest?module"></script>
<include-fragment id="suggest-as-template" src="https://github.github.io/include-fragment-element/examples/pull.html">
  <p>'Loading...</p>
</include-fragment>
```

```javascript
$('include-fragment').on('include-fragment-replaced', function () {
	console.log('hello');
})
```

In this example, "hello" is printed to the console twice, and it should only be triggered once, because the fragment is only replaced once. I do not know why this is happening. In other places it does seem to only trigger once.

### PR DESCRIPTION
**Pull request by koddsson**
Make sure not to fire off additional requests if there's already one in-flight. I chose to reflect this on the element through the read-only `busy` attribute.

Fixes #75

### CODE REVIEW

**Comment by koddsson** [comment]
This probably needs a failing test before the fix commit.

**Review by keithamus — APPROVED** [review]
Seems reasonable. Is it instead better to use AbortControllers to close previous requests, so that we always use the latest request?

**Comment by koddsson** [comment]
> Seems reasonable. Is it instead better to use AbortControllers to close previous requests, so that we always use the latest request?

Yeah, I think we could. I wanted to avoid doing multiple requests altogether though since I thought that was an error in itself.

**Comment by koddsson** [comment]
> > Seems reasonable. Is it instead better to use AbortControllers to close previous requests, so that we always use the latest request?
> 
> Yeah, I think we could. I wanted to avoid doing multiple requests altogether though since I thought that was an error in itself.

I was gonna do this but then we still emit the event twice because `#getData` still fetches data from the `WeakMap` and we happily emit the event.

**Pull request merged**
